name: Build and Deploy Docker to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/deepshield:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/deepshield:latest

      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v2
        with:
          app-name: deepshield-backend-tanavi
          images: ghcr.io/${{ github.repository }}/deepshield:latest